# Generated by Django 6.0.4 on 2026-05-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Optica', '0003_subcategoria_producto_subcategoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('motivo', models.CharField(default='Examen de la vista', max_length=150)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
